//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFishHouseManagementSystemMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingTBL
    {
        public string name { get; set; }
        public int person { get; set; }
        public string Category { get; set; }
        public string email { get; set; }
        public decimal mobile { get; set; }
        public string address { get; set; }
    }
}
