//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFishHouseManagementSystemMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FishTicketDataEntities : DbContext
    {
        public FishTicketDataEntities()
            : base("name=FishTicketDataEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Admin> Admins { get; set; }
        public DbSet<BookingTBL> BookingTBLs { get; set; }
        public DbSet<FeedBackTB> FeedBackTBs { get; set; }
        public DbSet<NewsTB> NewsTBs { get; set; }
        public DbSet<UserTB> UserTBs { get; set; }
    }
}
