//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineFishHouseManagementSystemMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewsTB
    {
        public string news { get; set; }
        public string subject { get; set; }
        public System.DateTime date { get; set; }
        public string description { get; set; }
    }
}
